--- 
cwd: /var/www/jazztoolbox.com/app/current
log_file: log/mongrel.log
port: "8020"
user: mongrel
group: mongrel
environment: production
address: 127.0.0.1
pid_file: tmp/pids/mongrel.pid
servers: 1
